language: csharp
solution: RTMService.sln
notifications:
  email:
    on_success: always
    on_failure: always
  slack: srboeingdotnet:UIU3Bl3s8QViLrC2yS7GV9NI
mono: none
dotnet: 2.1
script:
  - chmod +x ./deploy.sh
  - dotnet restore
  - dotnet test ChatUnitTesting/
after_success:
  - ls -alh
  - ls ./RTMService
  - /bin/bash ./deploy.sh
