version: "3"
services:
  web:
    build: ./RTMService
    container_name: RTM
    ports:
      - "5004:80"
    depends_on:
      - db
      - redis
  db:
    image: "mongo:latest"
    container_name: mongodbnew
    ports:
      - "27018:27017"
  redis:
    image: "redis:alpine"
    container_name: redisnew
    ports:
      - "6379:6379"
